[CHORE] 디자인 시스템 및 라우팅 초기 설정
GrebbMe/grabbme-fe pull request #18
Opened 2024-09-23 20:16 UTC by PARKJEONGJOON

## 반영 브랜치
ex) chore/design-system-setting/11-> dev

## 📌 작업내용
- [ ] 디자인 시스템 초기 설정 
- [ ] 라우팅 초기 설정

## 📸 상세한 설명 (사진은 선택)
초기 FSD 구조가 아직 완전히 정해지지 않아서 app layer 위주로 설정했습니다.

✅ 디자인 시스템 초기 설정 
pretendard 폰트를 추가하고 styled-components 의 `createGlobalStyle`을 통해서 전역에서 사용할 수 있도록 추가했습니다.
( 웹 브라우저 간의 일관성을 유지하기 위해서 styled-reset 추가 )
디자인시스템 설정을 하는데에  styled-components의  `ThemeProvider` 을 사용했습니다. 

 `ThemeProvider`를 사용하면 별도 import 없이 공통 스타일을 처리하는데 편리 할 거 같아서 선택했습니다.
`export const FooterContainer = styled.div`
  background-color: ${({ theme }) => theme.color.primaryBlue};
  ${({ theme }) => theme.typo.title};
`; `
색상 , 타이포, 반응형 브레이크 포인트 정도만 설정된 상태입니다.

✅ 레이아웃
라우팅 초기 설정에 앞서 간단한 레이아웃 ( 헤더,푸터) 설정을 했습니다.

✅ 라우팅 설정
createBrowserRouter을 이용해서 라우터를 구현했습니다. 

기존 BrowserRouter로 감싸지 않고 RouterProvider을 이용해서 구성요소를 전달하고 활성화합니다.

중첩되어있는 경로는 children을 통해서 간단하게 중첩해서 사용할 수 있습니다 ( 레이아웃)

✅ vite 절대 경로 
vite에서는 절대경로를 위해서 해당 설정이 추가로 필요합니다.
`export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});`

app layer에서 처리한 레이아웃이나 스타일 같은 부분들이 shared나 entity에 있어야 되는거 같기도 합니다. 일단 app layer 말고 다른 layer에서는 사용하지 않는 부분이라서 app layer에 배치했는데 의견 주시면 감사하겠습니다.

## ✨ PR Checklist
- [x] PR 제목 양식은 알맞게 작성했나요?
- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있나요?
- [ ] 이슈는 close 되었나요?
- [x] Reviewers, Labels 는 등록하였나요?
- [x] 불필요한 주석, 코드는 제거하였나요

## 📗 참고 자료 (선택)

## 📢 리뷰 요구 사항 (선택)
```
export const LayoutContainer = styled.div`
`;
```
스타일을 작성할때 warning이 뜹니다. 
![image](https://github.com/user-attachments/assets/e52ae971-0c15-48aa-8b36-3abfbaffe7fd)

props가 있을때 타입지정을 해야할거라고 생각하고 있었는데, props가 없어도 warning이 뜨네요. 

혹시 어떻게 작성 해야 하는지 알려주시면 감사하겠습니다. 

## 🚩 후속 작업 (선택)

## ✅ 리뷰어 유의사항

closed #Issue_number

2024-09-24 05:08 UTC, ykdman commented on src/app/router/router.tsx
> +]);
```suggestion
const enum RouterPath {
  GithubLogin = 'github-login',
  SignUp = 'sign-up'
}

export const router: ReturnType<typeof createBrowserRouter> = createBrowserRouter([
  {
    path: '/',
    element: <Layout />,
    children: [
      {
        path: RouterPath.GithubLogin,
        element: <GithubLogin />,
      },
      {
        path: RouterPath.Signup,
        element: <SignUp />,
      },
    ],
  },
]);
```
하나의 의견 제시입니다!
위 의 코드 처럼 enum 으로 path 들을 가지고 관리하는것은 어떨까요??
하드코딩 성의 path를 최대한 지양할 수 있고,
변수화 하여 관리하면 더 편하지 않을 까 싶습니다!

2024-09-24 05:08 UTC, ykdman commented on src/app/styles/layout.style.ts
> +
```suggestion
import { styled } from 'styled-components';
import type { Styled } from 'styled-components';

export const LayoutContainer: Styled = styled.div`
  display: flex;
  flex-direction: column;
  width: 100%;
  min-height: 100vh;
`;

```

PR 내용 중 리뷰 요구사항에도 적어 주셨던 Type Annotation에 대한 warning 이 발생하는데
`Styled` 가 `styled` Type 이여서 해당 Type을 import 해서 타입 선언하면 warining이 해결 되는 것 같습니다!

- styled.d.ts
```typescript
export default styled;
// ... 중략
export type Styled = typeof styled;
```

2024-09-24 05:08 UTC, ykdman commented on src/app/styles/theme.ts
> +        lineHeight: string;
```suggestion
import { DefaultTheme } from 'styled-components';
type ColorKeys = [
  'pointPink',
  'white',
  'black100',
  'black80',
  'gray50',
  'gray30',
  'blue50',
  'blue30',
  'blue10',
];

interface TypoProperties {
  fontFamily: string;
  fontWeight: number;
  fontSize: string;
  lineHeight: string;
}

interface DeviceSize {
  desktop: string;
  tablet: string;
  mobile: string;
}

declare module 'styled-components' {
  export interface DefaultTheme {
    color: {
      [key in ColorKeys[number]]: string;
    };
    typo: {
      title: {
         [key in keyof TypoProperties]: TypoProperties[key];
         }
      } //...
     deviceSize: {
        [key in keyof DeviceSize]: string;
    }; //...
    
```
type 과 interfacce 를 사용해서 `DefaultTheme` 을 설정 할 때,
타입 지정에 대해 좀 더 간편하게 할 수 있을 것 같습니다!

2024-09-24 06:32 UTC, minzziPark commented on src/app/styles/globlaStyle.ts
> +  html, body, #root {
찾아보니 과거부터 reset에 대해서 여러 가지 의견이 있는 것 같아서 우리 프로젝트도 초기 세팅할 때 reset에 적용해야하는 태그들에 대해 의논을 해보면 좋을 것 같습니다!

2024-09-24 06:33 UTC, minzziPark commented on src/app/router/router.tsx
> +]);
저도 개인적으로 따로 enum이나 상수데이터를 활용해서 path를 관리하면 path 유지보수상 훨씬 편리한 것 같아요!
routing하다보면 여러 컴포넌트에서 path를 사용하는 경우가 굉장히 많더라고요!

2024-09-24 10:19 UTC, PARKJEONGJOON commented on src/app/styles/theme.ts
> +        lineHeight: string;
[6e48aeb8a159ba45f21a68da0d04d984fbb33f58](url) 반영했습니다!

2024-09-24 10:21 UTC, PARKJEONGJOON commented on src/app/styles/theme.ts
> +        lineHeight: string;
https://github.com/GrebbMe/grabbme-fe/pull/18/commits/6e48aeb8a159ba45f21a68da0d04d984fbb33f58
반영했습니다!

2024-09-24 10:21 UTC, PARKJEONGJOON commented on src/app/router/router.tsx
> +]);
https://github.com/GrebbMe/grabbme-fe/pull/18/commits/523735cdee01fb2633b65af71ab7472e404a557a
반영했습니다 감사합니다!

2024-09-24 10:24 UTC, PARKJEONGJOON commented on src/app/styles/globlaStyle.ts
> +  html, body, #root {
해당 부분 관성적으로 한 부분이 있는데, 제대로 찾아보겠습니다! 다음에 의논해요!

2024-09-24 13:45 UTC, Seung-wan commented on src/app/router/router.tsx
> +]);
enum이 가지는 문제들을 고려하면 상수로 표현하는게 더 괜찮지 않을까요?

2024-09-24 13:47 UTC, Seung-wan commented on src/app/styles/layout.style.ts
> +
요거는 린트를 끄는게 더 괜찮지 않을까요?
자동 추론을 이용하지 못하고 불필요하는 코드가 생기는 것 같아서요

2024-09-24 13:48 UTC, Seung-wan commented on src/app/styles/theme.ts
> +        lineHeight: string;
만들어진 theme 변수를 이용해서 타입을 잡아주면 되지 않을까요?

2024-09-24 14:02 UTC, Seung-wan commented on package.json
> +    "@types/styled-components": "^5.1.34",
devDependencies에 위치해야 하지 않을까요?

2024-09-24 14:02 UTC, Seung-wan commented on src/app/App.tsx
> +const App = (): React.ReactNode => {
컴포넌트 리턴 타입을 명시적으로 잡아주는 건 불필요한 코드인 것 같아요

2024-09-24 14:02 UTC, Seung-wan commented on src/app/layout/Footer.tsx
> +  return <FooterContainer>Footer</FooterContainer>;
스타일드 컴포넌트를 이렇게 멀리 떨어뜨려 놓는건 좋지 않을 것 같아요
컴포넌트 파일 내에 작성하거나 혹은 분리하더라도 같은 폴더 경로 내에 작성되면 좋을 것 같습니다

2024-09-24 14:02 UTC, Seung-wan commented on src/app/layout/Header.tsx
> +import { HeaderContainer } from '@/app/styles/index';
이렇게 표현할 수 있지 않을까요?
```suggestion
import { HeaderContainer } from '@/app/styles';
```

2024-09-24 14:02 UTC, Seung-wan commented on src/app/layout/Layout.tsx
> +import { LayoutContainer, MainContent } from '@/app/styles/index';
이렇게 가능하지 않나요?
```suggestion
import { Header, Footer } from '@/app/layout';
import { LayoutContainer, MainContent } from '@/app/styles';
```

2024-09-24 14:02 UTC, Seung-wan commented on src/app/routers/router.tsx
> +}
별도 파일에 분리되어 작성해주는게 좋을 것 같구요~
enum으로 작성하는 것과 상수로 작성하는 것의 차이를 고민해보시면 좋을 것 같습니다

2024-09-25 00:06 UTC, lgyn10 commented on src/app/layout/Footer.tsx
> +  return <FooterContainer>Footer</FooterContainer>;
저도 같은 생각입니다. 스타일드 컴포넌트는 컴포넌트를 정의한 파일 내에서 같이 작성되면 좋을 것 같아요.

2024-09-25 00:11 UTC, lgyn10 requested changes

2024-09-25 00:11 UTC, lgyn10 commented on src/pages/auth/ui/GithubLogin.tsx
> +export const GithubLogin = (): ReactNode => {
`: ReactNode` 
여기에도 리턴 타입 명시를 안해도 될 것 같습니다.

2024-09-25 04:04 UTC, WonJuneKim requested changes

2024-09-25 04:04 UTC, WonJuneKim commented on package.json
> +    "styled-reset": "^4.5.2"
해당 패키지를 설치한 목적성을 기재해주면 더 좋을거같아요!

2024-09-25 04:04 UTC, WonJuneKim commented on src/app/layout/Layout.tsx
> +        <Outlet />
Outlet에 대한 정의나 추가 설명이 필요할 거 같아요

2024-09-25 04:04 UTC, WonJuneKim commented on src/app/routers/router.tsx
> +export const router: ReturnType<typeof createBrowserRouter> = createBrowserRouter([
`ReturnType<typeof createBrowserRouter> = createBrowserRouter` 은 createBrowserRouter 을 설정할 때 기본적으로 들어가는 라인인가요?

2024-09-25 04:04 UTC, WonJuneKim commented on src/app/styles/layout.style.ts
> +  height: 100vh;
width에 대한 정의는 따로 없는건가요? 
+) height 설정을 vh로 가져간 이유가 궁금합니다

2024-09-25 04:04 UTC, WonJuneKim commented on src/app/styles/globlaStyle.ts
> +import Pretendard from '@/shared/assets/font/PretendardVariable.woff2';
`Pretendard` 와 `PretendardVariable`은 다른 글꼴 입니다. 디자인에서는 `Pretendard`로 설정되어있는데 그대로 사용하지 않으신 이유가 궁금합니다!

2024-09-25 04:04 UTC, WonJuneKim commented on src/app/styles/globlaStyle.ts
> +    font-weight: 100 900;
기본 글꼴 설정에 `font-style`과 `font-weight`를 선언하신 이유가 있을까요?

2024-09-25 04:04 UTC, WonJuneKim commented on src/shared/consts/routerPath.ts
> +  SignUp = 'sign-up',
라우팅 경로를 상수화 대신 enum으로 사용하신 이유가 있을까요??

2024-09-25 04:04 UTC, WonJuneKim commented on src/app/styles/theme.ts
> +  typo: {
color 와 typo는 각각 `별개의 속성` 이라고 생각하는데 하나의 `theme` 파일에 선언하신 이유가 궁금합니다

2024-09-25 04:04 UTC, WonJuneKim commented on src/app/styles/theme.ts
> +    desktop: '@media screen and min-width: 1024px',
반응형을 의도하신 부분으로 이해했습니다. 다만, 이 경우 px 단위는 적합하지 않다고 생각합니다!

2024-09-25 04:04 UTC, WonJuneKim commented on src/app/styles/theme.ts
> +    white: '#FFFFFF',
컬러의 네이밍의 경우 `Uppercase`를 주로 사용하는 것 같습니다.

2024-09-25 07:16 UTC, PARKJEONGJOON commented on src/app/styles/globlaStyle.ts
> +import Pretendard from '@/shared/assets/font/PretendardVariable.woff2';
Pretendard 폰트를 받아서 보는 중에 variable 폰트도 같이 있어서 사용했습니다! ,  하나의 파일로  스타일을 한번에 처리 하는게 장점이라고 생각했습니다.

2024-09-25 07:21 UTC, PARKJEONGJOON commented on src/app/styles/globlaStyle.ts
> +    font-weight: 100 900;
스타일은 명시적으로 노말 스타일을 선언 한거여서 지워도 될 것 같습니다!  가변 폰트를 사용하려면  font-weight  범위를 지정해야 되는 걸로 알아 선언했습니다.

2024-09-25 07:23 UTC, PARKJEONGJOON commented on src/shared/consts/routerPath.ts
> +  SignUp = 'sign-up',
enum에 대한 이해가 부족해서 사용했습니다. 해당 부분은 상수 사용이 더 나은 방법인거 같아서 수정하겠습니다!

2024-09-25 07:34 UTC, PARKJEONGJOON commented on src/app/styles/theme.ts
> +    white: '#FFFFFF',
저도 작성하면서 상수 네이밍 컨벤션이 없는거 같아서 고민을 했었는데 , 해당 부분 Uppercase로 바꾸겠습니다.

추가적으로 라우팅경로도 ROUTERPATH.LOGIN 이런식으로 표현할까 하는데 괜찮을까요?

2024-09-25 07:42 UTC, PARKJEONGJOON commented on src/app/styles/theme.ts
> +  typo: {
ThemeProvider 을 통해서 스타일을 전역적으로 일관성 있게 관리하려고 한번에 선언 했습니다!

2024-09-25 07:45 UTC, PARKJEONGJOON commented on src/app/layout/Layout.tsx
> +        <Outlet />
미흡했던 설명들 추가적으로 모두 작성하겠습니다!!

2024-09-25 08:21 UTC, WonJuneKim requested changes

2024-09-25 08:21 UTC, WonJuneKim commented on src/app/styles/globlaStyle.ts
> +    font-weight: 100 900;
추가로 해당 파일명에 오타가 있는거 같습니다.

2024-09-25 08:21 UTC, WonJuneKim commented on src/app/styles/theme.ts
> +  typo: {
그럼 항상 스타일 설정에 color, typo, devicesize에 대한 정보가 있어야하는지 궁금합니다. 
(ex. typo를 사용하지 않는 컴포넌트에 대한 처리)

2024-09-25 08:28 UTC, PARKJEONGJOON commented on src/app/styles/layout.style.ts
> +  height: 100vh;
레이아웃은 임시로 설정했던건데 수정 예정입니다!

2024-09-25 12:54 UTC, PARKJEONGJOON commented on src/app/styles/theme.ts
> +  typo: {
```const Footer = styled.div`

  background-color: ${({ theme }) => theme.color.PRIMARY_BLUE};
  color: ${({ theme }) => theme.color.WHITE};
```;

```const Item= styled.div`
  ${({ theme }) => theme.typo.title};
```;
제가 질문에 대해 이해를 잘 못하고 있는거 같습니다.. 
일단 이런식으로 필요에 따라 컴포넌트에서 적용하면 될거라고 의도 하고 작성했습니다! 
이렇게 보니까 import가 따로 필요하지 않은 대신 스타일 사용을 위해서 타이핑을 꽤 많이 해야되는것도 단점인거 같네요.

2024-09-25 12:58 UTC, PARKJEONGJOON commented on src/app/styles/theme.ts
> +    desktop: '@media screen and min-width: 1024px',
https://github.com/GrebbMe/grabbme-fe/pull/18/commits/c177c8a6d24368146e9266a447dd4bdf7e5e1a7a# 
수정했습니다!

2024-09-25 13:23 UTC, PARKJEONGJOON commented on src/app/routers/router.tsx
> +export const router: ReturnType<typeof createBrowserRouter> = createBrowserRouter([
https://github.com/GrebbMe/grabbme-fe/pull/18/commits/5b59c748552d2c0e32284aa012b79ff464d72c93#diff-3f1b0dfaac37ef69fad7b06118157c4f78c36ca4b3b0e85a7a715c2eecb0294a 
아닙니다! 수정 반영했습니다.

2024-09-25 13:27 UTC, PARKJEONGJOON commented on src/app/styles/layout.style.ts
> +  height: 100vh;
https://github.com/GrebbMe/grabbme-fe/pull/18/commits/c177c8a6d24368146e9266a447dd4bdf7e5e1a7a 
수정 ,반영했습니다!

2024-09-25 13:29 UTC, PARKJEONGJOON commented on src/pages/auth/ui/GithubLogin.tsx
> +export const GithubLogin = (): ReactNode => {
수정했습니다!https://github.com/GrebbMe/grabbme-fe/pull/18/commits/ba790618d3ec71b1a1d98b838b117771f0a17989

2024-09-25 19:16 UTC, Seung-wan commented on src/shared/consts/routerPath.ts
> +  SignUp = 'sign-up',
지금부터 습관을 들여보시면 좋을 것 같은데요. 
`더 나은 방법인거 같아서`라는 표현보다는 `상수로 관리하는 게 ~한 면에서 더 좋기 때문에`와 같이 이유 있는 답변을 작성해보도록 연습해보시면 좋을 것 같아요. 요런 습관은 학습하는 습관도 그렇고 기술 면접이나 회사에서 일을 하면서도 다 도움이 된다고 생각합니다~

2024-09-25 19:19 UTC, Seung-wan commented on src/app/styles/theme.ts
> +  typo: {
변경되지 않는 값이기 때문에 렌더링 최적화 관련 이슈도 없고 provider로 꽂아주는 건 문제가 되지 않는다고 생각이 드는데요
대신에 원준님이 처음에 말씀해주신 내용은 파일을 분리해보는 것도 괜찮을 것 같네요

2024-09-25 19:21 UTC, Seung-wan commented on src/app/styles/theme.ts
> +    desktop: '@media screen and min-width: 1024px',
1rem을 10px로 사용할 수 있도록 font-size 처리를 해주면 더 편리할 것 같네요

2024-09-26 03:03 UTC, PARKJEONGJOON commented on src/app/styles/theme.ts
> +    desktop: '@media screen and min-width: 1024px',
기본 16px로 하자는 이야기가 있었던거 같은데 10px으로 바꾸면 훨씬 덜 피로할거 같네요 감사합니다! https://github.com/GrebbMe/grabbme-fe/pull/18/commits/986798fd3bfc5c3f10db93aae8871000ba97e123

2024-09-26 03:46 UTC, PARKJEONGJOON commented on src/app/styles/theme.ts
> +  typo: {
작성하면서는 스타일 규모가 크지 않아서 한번에 작성해도 상관 없을것 같아서 작성했었는데
유지보수 측면에서 봤을때 모듈화 하는게 더 관리하기 쉬운 방법이라는 생각이 들어서 분리했습니다! 
https://github.com/GrebbMe/grabbme-fe/pull/18/commits/8ec6875ec0d8d92d4899b1af27d51464cae8d5c0

2024-09-26 05:37 UTC, lgyn10 approved these changes

2024-09-26 08:43 UTC, WonJuneKim approved these changes
수고하셨습니다! 추가 코멘트 확인 부탁드릴게요! 일단 코멘트 드린 내용만 수정해주시고 해당 PR은 이정도에서 마무리하는게 좋을거같아요 :)

2024-09-26 08:43 UTC, WonJuneKim commented on src/app/routers/router.tsx
> +
해당 줄에 줄 바꿈 처리가 되어있는건 lint 설정인가요?

2024-09-26 08:43 UTC, WonJuneKim commented on src/app/styles/color.ts
> +export type ColorType = typeof color;
color과 ColorType를 같이 export 해준 이유는 뭔가요?

2024-09-26 08:43 UTC, WonJuneKim commented on src/app/layout/layout.style.ts
> +    grid-template-columns: repeat(12, 8rem);
실제로 그리드 안에서만 컴포넌트를 배치하는 것이 아니기 때문에 추후 해당 옵션에 의해 발생할 수 있는 문제들이 있어요. PR 상에서 grid-template-columns 을 사용했다는 사실을 명시 해줬으면 좋겠어요!

2024-09-26 08:43 UTC, WonJuneKim commented on src/app/styles/device.ts
> +  DESKTOP: '@media (min-width: 76.5rem)',
rem은 root 의 크기에 대비된 길이인데 root 관련 width나 height 설정이 따로 되어 있는지 궁금합니다.

2024-09-26 08:43 UTC, WonJuneKim commented on src/app/styles/index.ts
> +export { typo } from './typo';
이 부분도 일관적이게 절대 경로를 사용하면 좋을거 같아요.

2024-09-26 08:58 UTC, PARKJEONGJOON commented on src/app/layout/layout.style.ts
> +    grid-template-columns: repeat(12, 8rem);
넵 감사합니다 !

2024-09-26 09:11 UTC, PARKJEONGJOON commented on src/app/routers/router.tsx
> +
아닙니다! 수정했습니다 ㅠㅠ

2024-09-26 09:34 UTC, PARKJEONGJOON commented on src/app/styles/color.ts
> +export type ColorType = typeof color;
해당 부분 수정했습니다!

2024-09-26 09:34 UTC, PARKJEONGJOON commented on src/app/styles/index.ts
> +export { typo } from './typo';
감사합니다~~

2024-09-26 10:15 UTC, merged