로그인/회원가입 로직 구현 및 퍼블리싱
GrebbMe/grabbme-fe pull request #70
Opened 2024-10-14 01:32 UTC by lgyn10

## 반영 브랜치
ex) feat/auth/51 -> dev

## 📌 작업내용
- [ ] axios 라이브러리 추가
- [ ] 소셜 로그인 버튼 및 로직 구현
- [ ] Header에 소설 로그인 버튼 교체
- [ ] 사용할 일 없는 login 라우트 제거
- [ ] 불필요한 페이지 컴포넌트 제거
- [ ] 카테고리 목록을 가져오는 커스텀 훅 구현
- [ ] 회원가입 페이지 구현 및 퍼블리싱

## 📸 상세한 설명 (사진은 선택)
 
 

### ✅ 불필요한 요소 제거

`router.tsx`에서 login 라우터가 필요 없기에, 제거하였습니다. 
로그인 버튼을 누르면, 백엔드에서 `signup` 페이지로 리다이렉트 해주기 때문입니다. 

이에 따라, `GithubLogin.tsx`와 `Login.tsx`는 page 슬라이스에서 불필요하여 제거했습니다. 
이 기능은 feature의 `SocialLogin`이 대체합니다. 

### ✅ 소셜 로그인 버튼 구현

로그인 플로우는 다음과 같습니다. 이는 피그마의 `플로우 차트` 페이지에서 확인할 수 있습니다. 
<img width="1223" alt="스크린샷 2024-10-14 오전 10 17 20" src="https://github.com/user-attachments/assets/554c956d-a65a-46c5-801e-e28f5ac398be">

```tsx
export const SocialLogin = () => {
  const CLIENT_ID: string = import.meta.env.VITE_GITHUB_LOGIN_CLIENT_ID;
  const REDIRECT_URI: string = 'http://localhost:5173/';

  const authroizeGithubLogin = useCallback((): void => {
    const url: string = `https://github.com/login/oauth/authorize?client_id=${CLIENT_ID}&redirect_uri=${REDIRECT_URI}&scope=read:user user:email`;
    window.location.href = url;
    // CLIENT_ID가 절대로 변경되지 않을 것이라고 확신되어 esLint를 끔
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return <Button onClick={authroizeGithubLogin}>로그인</Button>;
};
```
다음과 같이 로그인 버튼을 클릭하면 로직은 다음과 같습니다. 

`비회원인 경우`, 백엔드에서 `/sginup`으로 리다이렉트를 해줘서 회원가입 페이지로 이동합니다. 여기서 필수 정보를 입력 후 완료 버튼을 누르면 백엔드에서 토큰을 발급해줍니다.  이 토큰을 프론트에서 쿠키에 저장합니다. 

`회원인 경우`, 백엔드에서 `REDIRECT_URI` `http://localhost:5173/`로 리다이렉트 해주며 랜딩페이지로 이동합니다. 여기에서는 백엔드가 토큰을 쿠키에 저장합니다. 

> `eslint-disable-next-line react-hooks/exhaustive-deps`와 같이 강제로 해당 부분을 임시로 린트를 꺼뒀습니다.
CLIENT_ID는 변동이 없기에 해당 조치를 취합니다. 추후 해당 린트를 완전히 끄는 것을 논의하고 싶습니다. 

### ✅ public 카테고리 목록들을 가져오는 훅 구현
`useFetchCategories.ts`파일에
- position-categories
- carrer-categories
- stack-categories
- project-categories
를 가져오는 API 호출 함수를 한 함수로 정의했습니다. 

### ✅ 회원가입 페이지 구현 및 퍼블리싱
현재 백엔드 API 배포가 이루어지지 않았기에, `POSITION_LIST`, `CAREER_YEAR_LIST`, `CATEGORY`, `STACK` 으로 하드 코딩하여 값을 넣어뒀습니다. 
이는 추후 `const { jobPosition, careerYear, techStackList, categoryList } = useFetchCategories();`를 통해 백엔드에서 값을 가져와 연결될 예정입니다. 

`/user`로 `POST` 요청을 통해 회원가입 요청을 보냅니다. 
body에 userDataForBE를 답아 보내고, body로 access token 과 refresh token을 받아 쿠키에 저장합니다.
아래는 백엔드에서 선언한 변수명에 맞게 이름을 변경하여 객체로 보내는 코드입니다. 
```tsx
const userDataForBE = {
        email,
        nickname,
        position_category_id: selectedJobPosition,
        carrer_category_id: selectedCareerYear,
        stack_category_id: selectedTechStackList,
        project_category_id: selectedCategoryList,
      };

## ✨ PR Checklist
- [ ] PR 제목 양식은 알맞게 작성했나요?
- [ ] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있나요?
- [ ] 이슈는 close 되었나요?
- [ ] Reviewers, Labels 는 등록하였나요?
- [ ] 불필요한 주석, 코드는 제거하였나요?

## 📗 참고 자료 (선택)

## 📢 리뷰 요구 사항 (선택)

## 🚩 후속 작업 (선택)

## ✅ 리뷰어 유의사항

closed #51

2024-10-14 16:48 UTC, Seung-wan commented on package.json
> +    "axios": "^1.7.7",
ky와 같은 라이브러리도 고려해보셔도 좋을 것 같습니다~

2024-10-14 16:48 UTC, Seung-wan commented on src/app/layout/Header.tsx
> +
굳이 작성한다면 전체 주석으로 표현되는게 나을 것 같습니다~

2024-10-14 16:48 UTC, Seung-wan commented on src/features/auth/ui/SocialLogin.tsx
> +    <Button icon={<IcGithubFilld />} onClick={authroizeGithubLogin}>
편집기에서 에러가 발생하지 않으시나요?
Button 컴포넌트는 variant와 size 속성을 필수로 받아야 합니다~

2024-10-14 16:48 UTC, Seung-wan commented on src/features/auth/ui/SocialLogin.tsx
> +  }, []);
저는 CLIENT_ID와 REDIRECT_URI 모두 컴포넌트 밖으로 분리하는게 더 적절할 것 같습니다~
그리고 이 케이스에서 CLIENT_ID가 변경이 되지 않는 값이라고 해도 deps에 해당 값을 넣어주는게 더 적절할 것 같네요

2024-10-14 16:48 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +const areAllTrue = (obj: CheckList): boolean => {
타입을 CheckList로 잡을거면 함수 이름이 변경되는게 좋을 것 같은데요.
함수의 동작을 생각하면 특정 맥락에 의존하지 않고 사용할 수 있을만한 함수라서 유틸 함수로 작성해봐도 좋을 것 같습니다.

2024-10-14 16:48 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +  console.log(jobPosition, careerYear, techStackList, categoryList);
console은 제거해주세요

2024-10-14 16:48 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +  const handleCheckboxChange = (checkItem: string) => {
타입이 조금 더 좁혀지면 좋을 것 같아요

2024-10-14 16:48 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +    }
1. 기존 상태값을 이용해서 새로운 상태를 만들때는 callback 함수를 이용해주세요.
2. else if, else를 제거해보시면 좋을 것 같습니다.

2024-10-14 16:48 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +        .post('/user', userDataForBE)
api 호출을 하는 함수는 별도로 api 계층을 만들어서 작성해주시면 좋을 것 같아요

2024-10-14 16:48 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +        .then((res) => {
async/await이 아닌 Promise 객체를 사용해주신 이유가 있으실까요?

2024-10-14 16:48 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +        .catch((err) => console.log(err));
에러처리는 제대로 되어야 할 것 같습니다

2024-10-14 16:48 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +          navigate('/');
라우팅 경로는 상수를 이용해서 표현해주시면 좋을 것 같아요

2024-10-14 16:48 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +          document.cookie = `refreshToken=${refreshToken}; path=/; max-age=${7 * 24 * 60 * 60}; secure; SameSite=Lax;`;
서버에서 Set-Cookie로 쿠키를 저장하지 않고 프론트엔드에서 저장하는 이유는 어떻게 될까요?

2024-10-14 16:48 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +        <TextFieldStyle>{'nickname'}</TextFieldStyle>
일반적으로 컴포넌트의 props에 문자열을 넘겨줄때는 중괄호를 사용하지 않지만 사용하는 것도 상관은 없다고 생각하는데요.
children으로 문자열을 넘길 때 중괄호를 쓰는 건 좋지 않은 것 같습니다.
```suggestion
        <InputHeader text='닉네임' isDetail={false} />
        <TextFieldStyle>nickname</TextFieldStyle>
```

2024-10-14 16:48 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +        <TextFieldStyle>{'nickname'}</TextFieldStyle>
nickname이 맞을까요?

2024-10-14 16:48 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +          placeholder="선택"
컨벤션을 맞춘다면 placeholder도 중괄호로 감싸져야 할 것 같은데요
이 부분에 대해서 프론트에서 컨벤션을 동일하게 가져가면 좋을 것 같습니다

2024-10-14 16:48 UTC, Seung-wan commented on src/shared/hooks/useFetchCategories.ts
> +      .then((careerRes) => {
Promise.all로 처리하는 건 어떨까요?

2024-10-14 16:48 UTC, Seung-wan commented on src/shared/hooks/useFetchCategories.ts
> +  return { jobPosition, careerYear, techStackList, categoryList };
비동기 동작을 다루는 데 있어서는 로딩과 에러 상태에 대한 처리가 무조건 들어가야합니다.
return값이 이렇게 되면 전혀 다룰 수 없을 것 같아요.

2024-10-14 16:48 UTC, Seung-wan commented on src/shared/ui/inputHeader/InputHeader.tsx
스토리 파일을 작성하지 않은 이유가 있으실까요?

2024-10-15 02:30 UTC, lgyn10 commented on package.json
> +    "axios": "^1.7.7",
프론트 회의에서 논의해보겠습니다!

2024-10-15 02:38 UTC, lgyn10 commented on src/features/auth/ui/SocialLogin.tsx
> +    <Button icon={<IcGithubFilld />} onClick={authroizeGithubLogin}>
저 또한 현재 dev 브랜치의 Button 컴포넌트는 variant와 size 속성을 받는 것으로 인지하고 있습니다! 
다만, 본 브랜치를 새로 팔 때 당시의 dev 브랜치에는 Button 컴포넌트가 수정되기 전이여서 사용법이 다른 상황입니다.

즉, 현재 버튼 컴포넌트를 따라 코드를 작성하면 `feat/auth/51` 브랜치에서는 에러가 납니다...!

이럴 때는 어떻게 개발 프로세스가 이루어져야 하는가에 대해서 궁금합니다. 현재로서는 머지 이후에 다시 hotfix로 버튼을 수정하는 식으로 처리해왔습니다!

2024-10-15 02:41 UTC, lgyn10 commented on src/features/auth/ui/SocialLogin.tsx
> +  }, []);
```tsx
const CLIENT_ID: string = import.meta.env.VITE_GITHUB_LOGIN_CLIENT_ID;
const REDIRECT_URI: string = 'http://localhost:5173/';

export const SocialLogin = () => {
  const authroizeGithubLogin = useCallback((): void => {
    const url: string = `https://github.com/login/oauth/authorize?client_id=${CLIENT_ID}&redirect_uri=${REDIRECT_URI}&scope=read:user user:email`;
    window.location.href = url;
  }, []);

  return (
    <Button icon={<IcGithubFilld />} onClick={authroizeGithubLogin}>
      로그인
    </Button>
  );
};
```

2024-10-15 04:00 UTC, lgyn10 commented on src/pages/auth/ui/SignUp.tsx
> +        .catch((err) => console.log(err));
보통 이런 류의 에러처리는 어떻게 하는지 궁금합니다...! 
이 경우에는 서버와의 통신 실패인데, 이럴 때는 `에러 안내 페이지` 같은 것을 만들어서 리다이렉트하는 방식일까요?

2024-10-15 04:20 UTC, lgyn10 commented on src/app/layout/Header.tsx
> +
넵!

2024-10-15 04:21 UTC, lgyn10 commented on src/features/auth/ui/SocialLogin.tsx
> +  }, []);
[70c5f15](https://github.com/GrebbMe/grabbme-fe/pull/70/commits/70c5f15d42357db26a12e745f5e1faee74dab557)에서 반영했습니다!

2024-10-15 04:21 UTC, lgyn10 commented on src/pages/auth/ui/SignUp.tsx
> +const areAllTrue = (obj: CheckList): boolean => {
[b403423](https://github.com/GrebbMe/grabbme-fe/pull/70/commits/b403423ab52d6956ca857aa4b2ce6c3746912d83)에서 
타입을 좁히고, util 함수로 분리했습니다!

2024-10-15 04:22 UTC, lgyn10 commented on src/pages/auth/ui/SignUp.tsx
> +  console.log(jobPosition, careerYear, techStackList, categoryList);
[f76abf5](https://github.com/GrebbMe/grabbme-fe/pull/70/commits/f76abf580bee5b2ab79435490f60926a2193ab9f)에서 반영했습니다!

2024-10-15 04:22 UTC, lgyn10 commented on src/pages/auth/ui/SignUp.tsx
> +  const handleCheckboxChange = (checkItem: string) => {
[2f001a2](https://github.com/GrebbMe/grabbme-fe/pull/70/commits/2f001a29c1dc494c7e18f35d660b3cb6740959c8)에서 반영했습니다.

2024-10-15 04:23 UTC, lgyn10 commented on src/pages/auth/ui/SignUp.tsx
> +    }
@Seung-wan 
[c8b563b](https://github.com/GrebbMe/grabbme-fe/pull/70/commits/c8b563b03ee65e81b8db45fb3465b34b2d068c7b)에서 반영했습니다! 의도하신 코드가 맞을까요??

2024-10-15 04:24 UTC, lgyn10 commented on src/pages/auth/ui/SignUp.tsx
> +        .then((res) => {
더 익숙해서 다음과 같이 사용했는데요!
async/await과 try/catch 문을 사용하는게 일반적인 것 같군요!

2024-10-15 04:24 UTC, lgyn10 commented on src/pages/auth/ui/SignUp.tsx
> +        .post('/user', userDataForBE)
[1d22c67](https://github.com/GrebbMe/grabbme-fe/pull/70/commits/1d22c673c4e78bb3a011798c34f456d357425d4f)에서 반영했습니다!

2024-10-15 04:25 UTC, lgyn10 commented on src/pages/auth/ui/SignUp.tsx
> +          navigate('/');
아직 메인 페이지가 상수화되지 않아서 명시적으로 적어뒀습니다..! 메인 페이지 작업하시는 분께서 상수화하시면 해당 값을 사용하겠습니다!

2024-10-15 04:26 UTC, lgyn10 commented on src/pages/auth/ui/SignUp.tsx
> +        <TextFieldStyle>{'nickname'}</TextFieldStyle>
넵! 이 부분은 [b650dcc](https://github.com/GrebbMe/grabbme-fe/pull/70/commits/b650dcc7df112572cfc7a905cd0b7612638025b6)에서 수정하였습니다! 
좀 더 꼼꼼하게 살피지 못했습니다!

2024-10-15 04:26 UTC, lgyn10 commented on src/pages/auth/ui/SignUp.tsx
> +        <TextFieldStyle>{'nickname'}</TextFieldStyle>
아닙니다 ㅠㅠㅠ 수정했습니다!

2024-10-15 04:27 UTC, lgyn10 commented on src/pages/auth/ui/SignUp.tsx
> +          placeholder="선택"
이런 부분도 컨벤션을 가져간다는 것을 이번에 인지하게 되었습니다. 기존 팀원들과 동일한 컨벤션으로 수정하겠습니다!

2024-10-15 04:39 UTC, lgyn10 commented on src/shared/ui/inputHeader/InputHeader.tsx
다른 팀원이 작성한 헤더 부분이 dev에 머지되기 전에 필요해서 가져왔습니다..!

2024-10-15 04:46 UTC, lgyn10 commented on src/pages/auth/ui/SignUp.tsx
> +          document.cookie = `refreshToken=${refreshToken}; path=/; max-age=${7 * 24 * 60 * 60}; secure; SameSite=Lax;`;
이 부분은 백엔드 파트에서 요청이 있었습니다!
서버에서 쿠키로 저장하기 어려울 것 같다고 말씀주셔서, 프론트에서 처리했습니다!

2024-10-15 05:43 UTC, lgyn10 commented on src/shared/hooks/useFetchCategories.ts
> +      .then((careerRes) => {
Promise.all로 처리해보려 하는데

> 199:5   error    Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

이런 린트 에러가 지속적으로 뜨는데, 해결 방법을 찾지 못해 일단은
```
// eslint-disable-next-line @typescript-eslint/no-floating-promises
```
으로 린트 무효화를 했습니다...!

코드는 다음과 같습니다! 
```tsx
import axios from 'axios';
import { useEffect, useState } from 'react';
import { SelectItem } from '@/shared/ui/select/MultiSelect';
import { SelectListItem } from '@/shared/ui/select/SelectList';

interface PositionCategory {
  position_category_id: number;
  kor_name: string;
}

interface CareerCategory {
  career_category_id: number;
  content: string;
}

interface StackCategory {
  stack_category_id: number;
  kor_name: string;
}

interface ProjectCategory {
  project_category_id: number;
  kor_name: string;
}

interface CategoryData {
  jobPosition: SelectListItem[] | null;
  careerYear: SelectListItem[] | null;
  techStackList: SelectItem[] | null;
  categoryList: SelectItem[] | null;
  isLoading: boolean;
  error: string | null;
}

export const useFetchCategories = (): CategoryData => {
  const [jobPosition, setJobPosition] = useState<SelectListItem[] | null>(null);
  const [careerYear, setCareerYear] = useState<SelectListItem[] | null>(null);
  const [techStackList, setTechStackList] = useState<SelectItem[] | null>(null);
  const [categoryList, setCategoryList] = useState<SelectItem[] | null>(null);

  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchAllCategories = async () => {
      setIsLoading(true);
      setError(null);
      try {
         const [positionRes, careerRes, stackRes, categoryRes] =  await Promise.all([
          axios.get('/public-data/position-categories'),
          axios.get('/public-data/carrer-categories'),
          axios.get('/public-data/stack-categories'),
          axios.get('/public-data/project-categories'),
        ]);
        setJobPosition(
          positionRes.data.map(
            (item: PositionCategory): SelectListItem => ({
              value: item.position_category_id.toString(),
              label: item.kor_name,
            }),
          ),
        );
        setCareerYear(
          careerRes.data.map(
            (item: CareerCategory): SelectListItem => ({
              value: item.career_category_id.toString(),
              label: item.content,
            }),
          ),
        );
        setTechStackList(
          stackRes.data.map(
            (item: StackCategory): SelectItem => ({
              id: item.stack_category_id,
              item: item.kor_name,
            }),
          ),
        );
        setCategoryList(
          categoryRes.data.map(
            (item: ProjectCategory): SelectItem => ({
              id: item.project_category_id,
              item: item.kor_name,
            }),
          ),
        );
      } catch (error) {
        setError('데이터를 불러오는 중 오류가 발생했습니다.');
        console.error('Error fetching categories:', error);
      } finally {
        setIsLoading(false);
      }
    };
// eslint-disable-next-line @typescript-eslint/no-floating-promises
    fetchAllCategories();
  }, []);

  return { jobPosition, careerYear, techStackList, categoryList, isLoading, error };
};
```

2024-10-15 05:44 UTC, lgyn10 commented on src/shared/hooks/useFetchCategories.ts
> +      .then((careerRes) => {
[097092](https://github.com/GrebbMe/grabbme-fe/pull/70/commits/d0970928a781102af378490c33c919085bff1839)에서 반영했습니다!

2024-10-15 05:44 UTC, lgyn10 commented on src/shared/hooks/useFetchCategories.ts
> +  return { jobPosition, careerYear, techStackList, categoryList };
[097092](https://github.com/GrebbMe/grabbme-fe/pull/70/commits/d0970928a781102af378490c33c919085bff1839)에서 반영했습니다!

2024-10-15 08:29 UTC, WonJuneKim requested changes
로그인 회원가입 로직 고생 많으셨습니다! 현재 몇가지 문제점을 발견했는데요, 
1) 이전에 구현되었던 버튼, 스택 카테고리 및 기타 컴포넌트가 삭제 처리 되는 거 같습니다.(베이스가 되는 브랜치 시점과 관련이 있는 거 같아요.) 이와 동일하게 추가되었던 설정들도 다시 delete 처리가 되네요!
2) UI Test의 `accept all`의 경우 해당 PR이 approve 되는 시점에 accept 해주시면 됩니다. 먼저 누르면 수정되지 않은 사항이 chromatic에 저장되니 이 부분 다시 한번 노티드립니다!

2024-10-15 08:29 UTC, WonJuneKim commented on src/app/layout/Layout.tsx
> +        <Wrapper>
해당 명칭은 이전 PR에서 명칭이 변경된걸로 아는데, 다시 수정하신 이유가 있을까요?

2024-10-15 08:29 UTC, WonJuneKim commented on src/app/layout/layout.style.ts
> +export const Wrapper = styled.div`
해당 부분도 동일합니다!

2024-10-15 08:29 UTC, WonJuneKim commented on src/app/styles/color.ts
> -  BLUE_50_25: 'rgba(142, 152, 169, 0.25)',
해당 부분은 민지님 PR에서 그림자 효과를 위해 추가되었는데, 삭제된 이유가 있을까요?

2024-10-15 08:29 UTC, WonJuneKim commented on src/features/auth/ui/SocialLogin.tsx
> +  }, [CLIENT_ID]);
해당 로직을 ui에 선언하신 이유가 있을까요?

2024-10-15 08:29 UTC, WonJuneKim commented on src/pages/auth/api/registerUser.ts
> +interface User {
```suggestion
import axios from 'axios';

interface User {
```
줄바꿈 처리가 되면 좋을 거 같네요!

2024-10-15 08:29 UTC, WonJuneKim commented on src/pages/auth/api/registerUser.ts
> +    console.error('User registration failed:', error);
사람마다 다르게 느낄 수도 있는데 저의 경우 이런 콘솔은 테스트 용이라면 한국어로 처리합니다!

2024-10-15 08:29 UTC, WonJuneKim commented on src/pages/auth/api/registerUser.ts
> +export const registerUser = async (userDataForBE: User) => {
```suggestion
export const registerUser = async (userData: User) => {
```

정도로만 표현해도 좋을 거 같네요!

2024-10-15 08:29 UTC, WonJuneKim commented on src/pages/auth/api/registerUser.ts
> +    document.cookie = `refreshToken=${refreshToken}; path=/; max-age=${7 * 24 * 60 * 60}; secure; SameSite=Lax;`;
BE에서 기본적으로 쿠키의 유효기간을 설정해주지 여부도 궁금합니다!

2024-10-15 08:29 UTC, WonJuneKim commented on src/pages/auth/ui/SignUp.tsx
> +const POSITION_LIST = [
이런 값들은 임시로 선언하더라도, ui가 아닌 consts에 작성하면 좋을거같아요!

2024-10-15 08:29 UTC, WonJuneKim commented on src/pages/auth/ui/SignUp.style.ts
> +export const NickNameContainer = styled.div`
보통 최상위 단위를 container로 잡고, 그 하위 항목은 ~~Wrapper로 선언하는 것도 좋습니다. 해당 부분은 참고만 하시면 될거 같아요!

2024-10-15 08:29 UTC, WonJuneKim commented on src/pages/auth/ui/SignUp.style.ts
> +    display: flex;
```suggestion
 export const HeaderLabel(혹은 HeaderBox) = styled.span`
    display: flex;
    ...
```
로 처리하는건 어떨까요?

2024-10-15 08:29 UTC, WonJuneKim commented on src/pages/auth/ui/SignUp.tsx
> +  };
이런 비즈니스 로직이나 api 호출 관련 부분은 ui에서 처리하지 않아도 된다고 생각합니다!

2024-10-15 08:29 UTC, WonJuneKim commented on src/pages/auth/ui/SignUp.tsx
> +      selectedCategoryList?.length
유효성 검사를 하는 hook이나 react-hook-form 을 사용하는 방식이 더 효율적인거 같네요!

2024-10-15 08:29 UTC, WonJuneKim commented on tsconfig.app.json
> +  "include": ["src"]
해당 부분도 이전 PR에서 수정된 부분인데 롤백된거 같습니다!

2024-10-15 08:29 UTC, WonJuneKim commented on src/shared/util/areAllChecked.ts
> +export const areAllChecked = (obj: CheckList): boolean => {
개인적인 선호일 수 있는데, 이런 유틸리티 함수명은 보통 동사형보다는 기능 중심으로 작성하는거 같네요!

2024-10-15 08:29 UTC, WonJuneKim commented on src/shared/ui/textfield/TextField.tsx
> +      </S.Header>
이 부분도 잘못 추가 되었을 수 있네요! 한번 점검 부탁드려요~

2024-10-15 08:29 UTC, WonJuneKim commented on src/shared/ui/index.ts
> +export { Button } from '@/shared/ui/button/Button';
이 부분도 기존 설정으로 롤백된 거 같네요! Button의 경우 default as 가 맞습니다!

2024-10-15 08:29 UTC, WonJuneKim commented on src/shared/ui/button/Button.tsx
> +export const Button = ({ children, onClick, disabled = false, icon, iconType }: ButtonProps) => (
버튼 컴포넌트가 이전 버전으로 설정 되어있습니다! 수정 전이 옳은 설정입니다!

2024-10-15 08:29 UTC, WonJuneKim commented on src/shared/ui/button/Button.style.ts
> +export const StyledButton = styled.button<{ icon?: ReactElement }>`
해당 스타일 코드도 동일하게 전 버전이 옳은 스타일 입니다!

2024-10-15 08:29 UTC, WonJuneKim commented on src/shared/ui/button/Button.stories.tsx
> +  title: 'shared/Button',
이 스토리 북 파일도 이전 설정이 맞네요!

2024-10-15 08:29 UTC, WonJuneKim commented on src/shared/assets/index.ts
> -export { default as IcSend } from '@/shared/assets/svg/IcSend.svg?react';
이 부분은 현재 사용 중인 부분입니다!

2024-10-15 08:29 UTC, WonJuneKim commented on src/shared/hooks/useFetchCategories.ts
> +export const useFetchCategories = (): CategoryData => {
카테고리 관련 제어를 해주는 hook의 경우 shared에는 다소 부적절하다는 생각이 있네요! 또한 api 호출 부분과 실제 데이터를 패칭하는 부분은 더 나누어 봐도 좋다는 생각입니다!

2024-10-15 17:38 UTC, Seung-wan commented on src/features/auth/ui/SocialLogin.tsx
> +    <Button icon={<IcGithubFilld />} onClick={authroizeGithubLogin}>
첫 개발하는 시점이라면 특정 브랜치를 기준으로 새 브랜치를 만드는게 가장 이상적인 것 같구요.
특정 커밋만 cherry-pick으로 꺼내오거나, 간단한 변경사항이라면 코드를 긁어오는 것도 괜찮을 것 같습니다.

2024-10-15 17:41 UTC, Seung-wan commented on src/features/auth/ui/SocialLogin.tsx
> +  }, [CLIENT_ID]);
이 주석은 제거되어야 하지 않을까요?
그리고 의존성에 값이 제거되어야 할 것 같습니다.

2024-10-15 17:41 UTC, Seung-wan commented on src/shared/util/areAllChecked.ts
> +export const areAllChecked = (obj: CheckList): boolean => {
적절한 네이밍과 타입이 아닌 것 같습니다.

2024-10-15 17:42 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +    }
넵~ 맞습니다!

2024-10-15 17:43 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +        .then((res) => {
엄연히는 동작이 같지 않기 때문에 사용하기 나름이라고 봐주시는게 맞을 것 같습니다~

2024-10-15 17:44 UTC, Seung-wan commented on src/pages/auth/ui/SignUp.tsx
> +        .catch((err) => console.log(err));
이 경우에는 Toast 또는 Alert을 띄워주는게 제일 적절하지 않을까 싶습니다~

2024-10-17 04:41 UTC, PARKJEONGJOON approved these changes

2024-10-17 04:41 UTC, closed without merging